### ISSUE TITLE
Removing a CVC as part of P2V is not returning the Nic to the Default Network

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#404] opened 2016-03-08 17:25 UTC
1. Have a reservation with D.App that connected to Vlan  (connect the CVC)
2. remove the CVC
BIR: if the D.App's Nic is not returning to the default network "Anetwork"

**Comment by doppleware** [comment] 2016-03-08 18:18
Duplicate of #256

**Closed** 2016-03-09 21:55 UTC
Labels: bug, CVC, duplicate
