### ISSUE TITLE
CVC: Selected Network Attribute is empty when the connection is between Vlan to D.App

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#286] opened 2016-02-29 14:28 UTC
1. have reservation with D.App and Vlan service
2. add a CVC between them
3. connect the CVC

BIR: if the Selected Network Attribute is empty and not with the Vlan ID

**Comment by alexazarh** [comment] 2016-02-29 14:41
From what I know its the desired behavior...
@alonagetzler / @doppleware - please confirm

**Comment by alonagetzler** [comment] 2016-03-09 12:25
its as designed, not a bug,

**Comment by TomerAdmon** [comment] 2016-03-14 17:42
closing after alona's comment below

**Closed by TomerAdmon** 2016-03-14 17:42 UTC
Labels: bug, Cancelled, P3
