### ISSUE TITLE
Three Test VM app concurrency deploy fails

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#475] opened 2016-03-17 07:50 UTC
Opened by Johnathan

1) Drag three Test VM apps
2) Connect them with CVC to form a triangle
3) Deploy each one one after another

BIR when refresh ip fails, or resource not found error appears (tried it twice, two separate errors)

Note: Tried it one more time when no one uses the bdt server (~5:20, when the bdt was over at 5:00), and it worked.

An example of a triangle:
![image](https://cloud.githubusercontent.com/assets/12639815/13839693/bcb11786-ec25-11e5-93f6-618a4d10c626.png)

Server log:
2016-03-15 06:39:04,125 [54] ERROR ResourceManager.TclAPI - [IP: 192.168.42.101, Machine: QS-SRV-TEST:8029 - Tcl, QualiSystems Username: admin]
Error retrieving resource: Test VM - EntityException [Error Code: EntityNotFound]: Entity 'Test VM' not found.
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.ExceptionsUtil.ThrowInvalidEntityOperationException(ErrorCode errorCode, String[] formatArgs)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByFullPath(String fullPath)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByNameOrPath(String entityFullName)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.TryGetLabResourceByFullName(String resourceFullName, LabResource& labResource, String& errorMessage)
2016-03-15 06:39:05,710 [64] ERROR ResourceManager.TclAPI - [IP: 192.168.42.101, Machine: QS-SRV-TEST:8029 - Tcl, QualiSystems Username: admin]
Error retrieving resource: Test VM2 - EntityException [Error Code: EntityNotFound]: Entity 'Test VM2' not found.
   at QualiSystems.Infrastructure.Hierarchy.Service.Core.ExceptionsUtil.ThrowInvalidEntityOperationException(ErrorCode errorCode, String[] formatArgs)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByFullPath(String fullPath)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.GetEntityByNameOrPath(String entityFullName)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ApplicationServicesHelper.TryGetLabResourceByFullName(String resourceFullName, LabResource& labResource, String& errorMessage)
2016-03-15 06:39:38,048 [ZeroMQ server worker thread] ERROR QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver - [Machine: QS-SRV-TEST, Domain Username: SYSTEM]
System.NullReferenceException: Object reference not set to an instance of an object.
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ResourceNameRetriever.GetResourceName(Guid resourceId)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompletedExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.InstantJobEventsLogExecutionObserver.ExecutionEnded(IInstantJob instantJob, Execution execution, ExecutionResult executionResult)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.<>c__DisplayClassa.<ExecutionEnded>b__9(IInstantJobExecutionObserver x)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.SafelyDoOnEachObserver(Action`1 action, Execution execution, IInstantJob instantJob)
2016-03-15 06:40:19,432 [ZeroMQ server worker thread] WARN  DistributedProvisioning.Execution - [Machine: QS-SRV-TEST, Domain Username: SYSTEM]
Power Command 'remote_refresh_ip' CommandFailed, Resource Id: '7c8d91fe-b66c-494c-8f60-7747ec538e9d', Connected Resource Id 'e473f1ec-8bfa-452d-8aef-de459220cdc8', Reservation '9b8aee88-c213-49f7-ba89-25f447cc8977', Execution Id: '1f04469a-6850-467a-a96c-5ca1c6f5dda0', Owner admin, Execution Server: 'BDT'
2016-03-15 06:40:19,511 [ZeroMQ server worker thread] WARN  DistributedProvisioning.Execution - [Machine: QS-SRV-TEST, Domain Username: SYSTEM]
Power Command 'remote_refresh_ip' CommandFailed, Resource Id: '7c8d91fe-b66c-494c-8f60-7747ec538e9d', Connected Resource Id 'a13ed5a5-a187-404c-8895-9e1e0d360e12', Reservation '9b8aee88-c213-49f7-ba89-25f447cc8977', Execution Id: 'b794e83b-8a2c-4d1f-a75d-d40ecc91b19d', Owner admin, Execution Server: 'BDT'
2016-03-15 06:40:19,898 [ZeroMQ server worker thread] ERROR QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver - [Machine: QS-SRV-TEST, Domain Username: SYSTEM]
System.NullReferenceException: Object reference not set to an instance of an object.
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ResourceNameRetriever.GetResourceName(Guid resourceId)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.FailedExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.InstantJobEventsLogExecutionObserver.ExecutionEnded(IInstantJob instantJob, Execution execution, ExecutionResult executionResult)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.<>c__DisplayClassa.<ExecutionEnded>b__9(IInstantJobExecutionObserver x)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.SafelyDoOnEachObserver(Action`1 action, Execution execution, IInstantJob instantJob)
2016-03-15 06:40:19,898 [ZeroMQ server worker thread] WARN  DistributedProvisioning.Execution - [Machine: QS-SRV-TEST, Domain Username: SYSTEM]
Resource Command 'deploy' Failed, Resource Id: '53995531-387c-4846-b5da-b146993ce258', Reservation Id '9b8aee88-c213-49f7-ba89-25f447cc8977', Execution Id: '35844835-6853-4ed1-a18d-c500e46e82fd', Owner 'johnathan.v', Execution Server: 'BDT', Output: 'Failed with error: 'Command execution failed with error: 'remote_refresh_ip'.
Error description: An unhandled exception occurred during command execution''
2016-03-15 06:40:20,833 [ZeroMQ server worker thread] ERROR QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver - [Machine: QS-SRV-PERFOR, Domain Username: SYSTEM]
System.NullReferenceException: Object reference not set to an instance of an object.
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ResourceNameRetriever.GetResourceName(Guid resourceId)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.FailedExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.ExecutionResultEventDescriptionFactory.CreateExecutionResultEventDescription(ExecutionResult executionResult, Execution execution)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.InstantJobEventsLogExecutionObserver.ExecutionEnded(IInstantJob instantJob, Execution execution, ExecutionResult executionResult)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.<>c__DisplayClassa.<ExecutionEnded>b__9(IInstantJobExecutionObserver x)
   at QS.TestShell.Server.ExecutionPlanner.InstantJobs.CompositeInstantJobExecutionObserver.SafelyDoOnEachObserver(Action`1 action, Execution execution, IInstantJob instantJob)
2016-03-15 06:40:20,833 [ZeroMQ server worker thread] WARN  DistributedProvisioning.Execution - [Machine: QS-SRV-PERFOR, Domain Username: SYSTEM]
Resource Command 'deploy' Failed, Resource Id: '0aa3398e-8d28-4634-9166-b2e08058864d', Reservation Id '9b8aee88-c213-49f7-ba89-25f447cc8977', Execution Id: 'cd79ea97-0a4d-4167-8e36-5c7e7ab9b455', Owner 'johnathan.v', Execution Server: 'Mogli', Output: 'Failed with error: 'Command execution failed with error: 'remote_refresh_ip'.
Error description: An unhandled exception occurred during command execution''

**Comment by doppleware** [comment] 2016-03-17 21:44
Probably duplicate of #298
Should be fixed by same changeset in TFS

**Comment by TomerAdmon** [comment] 2016-03-21 09:20
still reproduces: 

![image](https://cloud.githubusercontent.com/assets/12639815/13914407/e1a08750-ef56-11e5-98ad-9f231cfbaf3a.png)

connectivity failed:
command_json_result={"driverResponse": {"actionResults": [{"success": "False", "updatedInterface": "None", "errorMessage": "'str' object has no attribute 'name'", "infoMessage": "", "actionId": "6bc03478-3144-4835-84fe-39b0fe28109b_33684851-851f-4363-9f76-2fcafb226677", "type": "setVlan"}, {"success": "False", "updatedInterface": "None", "errorMessage": "'str' object has no attribute 'name'", "infoMessage": "", "actionId": "6bc03478-3144-4835-84fe-39b0fe28109b_6343a1fd-3898-44f1-b769-2a968082837b", "type": "setVlan"}, {"success": "False", "updatedInterface": "None", "errorMessage": "'str' object has no attribute 'name'", "infoMessage": "", "actionId": "2b9462eb-f398-4e69-87a2-1305e5df2401_6343a1fd-3898-44f1-b769-2a968082837b", "type": "setVlan"}, {"success": "False", "updatedInterface": "None", "errorMessage": "'str' object has no attribute 'name'", "infoMessage": "", "actionId": "2b9462eb-f398-4e69-87a2-1305e5df2401_aeb59c31-15cf-4752-8304-6a45ea7a5279", "type": "setVlan"}]}}=command_json_result_end

**Comment by TomerAdmon** [comment] 2016-03-21 09:22
@doppleware  - i removed the duplicate tag, seems not related i think

**Comment by doppleware** [comment] 2016-03-22 08:49
'str' object has no attribute 'name'",  was a regresssion yesterday since fixed.

**Comment by TomerAdmon** [comment] 2016-03-26 16:36
Verified

**Closed** 2016-03-26 16:36 UTC
Labels: bug, P1
