### ISSUE TITLE
When trying to connect two vlans to a vm using the same Requested target vNIC Name only one of the connection is connected while the other stays visually only connected

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#398] opened 2016-03-08 10:49 UTC
STR
Have a reservation with a deployed app in it connected to a vlan and the connection use the "Requested target vNIC Name " attribute
Add another vlan to the reservation
Connect the vlan to the deployed app using the Requested target vNIC Name with the same value as the previous connection

BIR
in the vcenter only the latest is connected while the other is not. on the reservation both of the connection seems to be connected

**Comment by doppleware** [comment] 2016-03-08 18:25
duplicate of #394

**Closed** 2016-03-09 21:55 UTC
Labels: bug, Connectivity, duplicate
