### ISSUE TITLE
Destroy VM action not returning the Nic of other connected VM to the Default value "Anetwork"

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#344] opened 2016-03-03 14:08 UTC
STR:
1. have reservation with 2 D.apps with connected  CVC between them
2. destory one of the D.app

BIR:
if the nic of the second D.app is not returning to the default value "Anetwork"

**Comment by razaba** [comment] 2016-03-08 12:31
Duplicate of #256

**Closed** 2016-03-09 21:55 UTC
Labels: bug, CVC, duplicate
