### ISSUE TITLE
when filling "VCENTER IMAGE ARGUMENTS" in " VM Deployed From Image" app, the field has no effect on the deployment

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#294] opened 2016-03-01 11:18 UTC
when filling "VCENTER IMAGE ARGUMENTS" in " VM Deployed From Image" app, the field has no effect on the deployment.

**Comment by doppleware** [comment] 2016-03-08 20:48
duplicate of #364

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
