### ISSUE TITLE
Failed connection stuck with "Connecting" and solid line (Connected==true)

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#500] opened 2016-03-20 13:58 UTC
### Issue details

Failed connection stuck with "Connecting" and solid line (Connected==true)

### Steps to reproduce

- have a DUT (device connected to L2) and a deployed app linked by CVC, but not connected
- Make sure the deployed app has NO network adapters (by configuring the VM this way)
- make sure there are NO available execution servers
- hit connect

Defect reproduces if:
- CVC has alias "Connecting" even after Apply Connectivity Changes command failed, and CVC appears as solid line (i.e. Connected==true)

Here is the JSON I got back:
	
'Apply Connectivity Changes' resource command on 'VMware vCenter' failed with 'Start Failed' error:
Error: Start Failed
Description: Execution server is unavailable
Parameters:

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by nahumtimerman** [comment] 2016-03-20 15:11
Mind, should be connected=false since both endpoints failed to apply

**Comment by alexazarh** [comment] 2016-03-21 09:14
Duplicate of #501

**Comment by TomerAdmon** [comment] 2016-03-26 16:42
close as it's duplicate

**Closed** 2016-03-26 16:42 UTC
Labels: bug, Connectivity, CVC, P2
