### ISSUE TITLE
Destroy App command raise non clear error when the deployed app (vm) is no longer exists in the vCenter

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#293] opened 2016-03-01 10:02 UTC
1.have a vm in the reservation
2. remove it from the vCenter
3. run the destroy app command
error:
Destroy App ended with status Failed with error: 'NoneType' object has no attribute 'config'

**Comment by doppleware** [comment] 2016-03-08 20:51
Duplicate of #159

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
