### ISSUE TITLE
vm deployment with wrong template route will bring unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#313] opened 2016-03-02 10:35 UTC
STR
Have a VM deployment with a false template rout in it 
Create a reservation
add the VM deployment app in it
run the deploy command 

BIR

![image](https://cloud.githubusercontent.com/assets/17527106/13457915/3c7746de-e073-11e5-81e9-9bae394cf261.png)

**Comment by doppleware** [comment] 2016-03-08 20:39
duplicate of #156

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
