### ISSUE TITLE
Unstabe: The "Delete" command on app resource failed with a strange error: Delete ended with status Failed with error: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#461] opened 2016-03-16 11:41 UTC
Delete command error on app-resource:
 
![image](https://cloud.githubusercontent.com/assets/12639815/13811196/daeffcd4-eb7c-11e5-8a22-5b51a65fddf9.png)

![image](https://cloud.githubusercontent.com/assets/12639815/13811205/ea77be3a-eb7c-11e5-8078-fd0f296713ed.png)

*** happened at 15:09 and also at 15:26.

**Comment by doppleware** [comment] 2016-03-16 20:26
Any logs?

**Comment by doppleware** [comment] 2016-03-17 08:06
maybe duplicate of 459

**Closed** 2016-04-05 20:28 UTC
Labels: bug, P3
