### ISSUE TITLE
Connectivity: When destroy a VM that connected to another VM not deleting the chosen vlan from the DB

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#402] opened 2016-03-08 15:58 UTC
STR:
1. Have a reservation with 2 D.Apps
2. Then add CVC and connect it 
3. destroy one of the D.apps

BIR:
if the vlan ID that was chosen in the CVC wasn't deleted from the DB

**Comment by doppleware** [comment] 2016-03-08 18:22
duplicate of #388

**Closed** 2016-03-09 21:54 UTC
Labels: bug, Connectivity, CVC, duplicate
