### ISSUE TITLE
If vm template not found during deploy get user unfriendly error

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#304] opened 2016-03-01 15:15 UTC
Deploy App ended with status Failed with error: CloudShellAPIError: Command execution failed with error: 'KeyError'.
Error description: vmomi managed object not found at: YOUR_FOLDER
[collection is empty]

**Comment by doppleware** [comment] 2016-03-08 20:43
Duplicate of #156

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
