### ISSUE TITLE
when removing "partially connected" CVC it not returning the NIC to the default value "Anetwork"

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#324] opened 2016-03-02 16:16 UTC
steps to rep:
1. have reservation with 2 APPs
2. add CVC connection between the 2 apps
3. then deploy one app (the alias name changed to "partially connected")
4. Then remove the CVC connection
 
Expected res:
after removing the CVC connection it supposed to return the NIC of the VM to the default value "Anetwork" and it still on the chosen Vlan

![image](https://cloud.githubusercontent.com/assets/17528399/13466534/00c0b6d6-e0a3-11e5-9226-bb1f09134ffb.png)

**Comment by doppleware** [comment] 2016-03-08 20:33
possibly duplicate of #256

**Closed** 2016-03-09 21:55 UTC
Labels: bug, duplicate
