### ISSUE TITLE
unclear error msg when there are no Nics available

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#326] opened 2016-03-02 17:32 UTC
![image](https://cloud.githubusercontent.com/assets/17528399/13468890/97b8e6bc-e0ad-11e5-9007-0235e0b2ebce.png)

**Comment by doppleware** [comment] 2016-03-08 20:23
DUPLICATE of #160

**Closed** 2016-03-09 21:55 UTC
Labels: bug, duplicate, Usability
