### ISSUE TITLE
Port Group:Not removing the Port Group in Vsphere when removing The Last CVC that related to that port group (Vlan ID)

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#287] opened 2016-02-29 14:37 UTC
1. have reservation with 2 D.Apps
2. have a Connected CVC between them
3. Verify that they are the only Vms that use the port Group that has been auto chosen 
4. then remove the CVC
 
BIR: if after the removing the port group in vSphere is still exist and there are no Vm's that use it.

* it will reproduce when connecting between D.App to Vlan Service and then removing the Vlan Service

**Comment by doppleware** [comment] 2016-03-09 09:10
Duplicate of #396

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
