### ISSUE TITLE
When having P2P connection between two vms and destroy one of them (or both) - the vlan\resource pool is not deleted from the db

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#379] opened 2016-03-07 07:51 UTC
have two deployed vms connected to vlan x
destroy one of the vms (or both)

BIR:
the vlan\resource pool does not being removed from the db and the vCenter

**Comment by razaba** [comment] 2016-03-08 12:27
Duplicate of #388

**Closed** 2016-03-08 15:48 UTC
Labels: bug, Cancelled, Connectivity, duplicate, P2
