### ISSUE TITLE
When creating a new enviroment and connecting two deployment app the connector is visual connector instead of cvc

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#320] opened 2016-03-02 14:57 UTC
STR
Create a new environment 
Add two VM Deployment apps
Connect the apps via p2p

BIR
The connection is visual instead of cvc
![image](https://cloud.githubusercontent.com/assets/17527106/13464056/ec7a4512-e097-11e5-8412-16dc15215775.png)

**Comment by doppleware** [comment] 2016-03-08 21:40
Could not reproduce on latest

**Comment by TomerAdmon** [comment] 2016-03-10 15:19
could not repreduce. closing.

**Closed** 2016-03-10 15:19 UTC
Labels: bug, P2
