### ISSUE TITLE
Destroy VM on a vm that was deleted manualy form vcenter will fail with massive error

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#159] opened 2016-02-01 14:31 UTC
##testcase: 148458

STR
1) deploy vm
2) delete the vm from Vcenter
3) execute destroy vm command

Destroy VM Proxy ended with status Failed with error: 01/Feb/2016 16:30:12 DEBUG Executing Destroy VM command on vCenter
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
<type 'unicode'>
Traceback (most recent call last):
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\tomer.a\AppData\Local\Temp\01fb9918-82ba-4c51-a828-f230d2ef1b06\Destroy VM Proxy.zip\__main__.py", line 10, in <module>
File "C:\Users\tomer.a\AppData\Local\Temp\01fb9918-82ba-4c51-a828-f230d2ef1b06\Destroy VM Proxy.zip\__main__.py", line 6, in main
File "C:\Users\tomer.a\AppData\Local\Temp\01fb9918-82ba-4c51-a828-f230d2ef1b06\Destroy VM Proxy.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 68, in destroy_vm
File "C:\Users\tomer.a\AppData\Local\Temp\01fb9918-82ba-4c51-a828-f230d2ef1b06\Destroy VM Proxy.zip\deployed_app_service\proxy\deployed_app_proxy.py", line 101, in execute_command_on_vcenter_resource
File "C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5127, in ExecuteCommand
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.

Error description: 01/Feb/2016 16:30:12 INFO action:START command_name:destroy

01/Feb/2016 16:30:12 INFO connecting to vcenter: 192.168.42.110

01/Feb/2016 16:30:12 DEBUG connection params: host: 192.168.42.110 username: administrator@vsphere.local port: 443

01/Feb/2016 16:30:13 INFO Starting new HTTPS connection (1): 192.168.42.110

01/Feb/2016 16:30:13 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 552

01/Feb/2016 16:30:13 INFO connected to vcenter: 192.168.42.110

01/Feb/2016 16:30:13 INFO executing command: destroy

01/Feb/2016 16:30:13 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',4222b7bd-7291-42b5-bbaf-b4169bbf4b78,test_cb1c21b2

01/Feb/2016 16:30:13 DEBUG Disconnect Interface VM: '4222b7bd-7291-42b5-bbaf-b4169bbf4b78' Network: 'ALL' ...

01/Feb/2016 16:30:13 DEBUG Disconnect Interface VM: '4222b7bd-7291-42b5-bbaf-b4169bbf4b78' Network: 'ALL' ...

01/Feb/2016 16:30:13 ERROR error has occurred while executing command: destroy

01/Feb/2016 16:30:13 ERROR 'NoneType' object has no attribute 'config'

Traceback (most recent call last):

File "C:\Users\tomer.a\AppData\Local\Temp\24e282d6-ad74-44a1-a55e-14e9deef1d7a\Destroy VM.zip\common\wrappers\command_wrapper.py", line 62, in execute_command_with_connection

results = command(*tuple(command_args))

File "C:\Users\tomer.a\AppData\Local\Temp\24e282d6-ad74-44a1-a55e-14e9deef1d7a\Destroy VM.zip\vCenterShell\commands\destroy_vm.py", line 26, in destroy

self.disconnector.disconnect_all(si, vm_uuid, vm)

File "C:\Users\tomer.a\AppData\Local\Temp\24e282d6-ad74-44a1-a55e-14e9deef1d7a\Destroy VM.zip\vCenterShell\commands\disconnect_dvswitch.py", line 48, in disconnect_all

return self.disconnect(si, vm_uuid, None)

File "C:\Users\tomer.a\AppData\Local\Temp\24e282d6-ad74-44a1-a55e-14e9deef1d7a\Destroy VM.zip\vCenterShell\commands\disconnect_dvswitch.py", line 74, in disconnect

return self.port_group_configurer.disconnect_all_networks(vm, default_network)

**Comment by alexazarh** [comment] 2016-04-05 20:57
duplicate of 505

**Closed** 2016-04-05 20:57 UTC
Labels: bug, P4
