### ISSUE TITLE
Should throw error when trying to connect an already connected port/vNic

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#221] opened 2016-02-22 15:27 UTC
in the scenario in which a connection request is made to an L2/L3 port that is already connected or to a vNIC that is already connected (the vNIC is specified on the connector itself) we need to get an error from the server that you should disconnect first

**Comment by doppleware** [comment] 2016-03-08 18:54
duplicate of #398

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate, VM Networking
