### ISSUE TITLE
Non clear error appears when having a wrong template path

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#283] opened 2016-02-29 13:14 UTC
Deploy App ended with status Failed with error: 29/Feb/2016 15:13:54 INFO Executing 'vCenter VM From Template' on app 'VM Deployment'...
29/Feb/2016 15:13:57 ERROR Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\38cd1b4d-6531-45a6-a22a-4405869def44\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\38cd1b4d-6531-45a6-a22a-4405869def44\Deploy.zip\__main__.py", line 10, in main&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\38cd1b4d-6531-45a6-a22a-4405869def44\Deploy.zip\driver.py", line 34, in execute&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 5152, in ExecuteCommand&#xD;
raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;
qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'ValueError'.&#xD;
&#xD;
Error description: Virtual Machine Template with name YairTemp1 was not found under folder QualiSB/Yair&#xD;
&#xD;
[collection is empty]</Error><ErrorCode>100</ErrorCode></Response>
Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><Error>Script runner exited with exit code: 1: Traceback (most recent call last):&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main&#xD;
"__main__", fname, loader, pkg_name)&#xD;
File "C:\work\TFS\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code&#xD;
exec code in run_globals&#xD;
File "C:\Users\yair.z\AppData\Local\Temp\38cd1b4d-6531-45a6-a22a-4405869def44\Deploy.zip\__main__.py", line 13, in &lt;module&gt;&#xD;

**Comment by doppleware** [comment] 2016-03-08 20:54
Duplicate of #156

**Closed** 2016-03-09 21:56 UTC
Labels: bug, duplicate
