### ISSUE TITLE
Choosing Specific Nic on CVC will override "reserved network"

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#530] opened 2016-03-22 11:49 UTC
### Issue details

Choosing Specific Nic on CVC will override "reserved network"

### Steps to reproduce

0) set vlan65 as a reserved network ino the vcenter resource
1) Create template in Vcenter with 2 Nics, one of them is vlan65 one of them is Anetowrk
2) Create an app for the template
3) Create new reservation and add the app
4) Deploy the app
5) Add vlan and connect it to the app
6) Open the CVC attributes, fill in the Vnic that allocated to vlan65 in the Vcenter

### Results
The reserved network is overritten by the "speficic Nic" request

related to test case 151950

**Comment by razaba** [comment] 2016-03-22 13:13
by design.
If you specify the adapter specifically it should override it.
Closing.

**Closed** 2016-03-22 13:13 UTC
Labels: bug, New, P2, ready
