### ISSUE TITLE
get label "Connecting" and solid line when no execution server after apply connectivity failed

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#501] opened 2016-03-20 14:11 UTC
### Issue details

Failed connection stuck with "Connecting" and solid line (Connected==true)

### Steps to reproduce

- have a DUT (device connected to L2) and a deployed app linked by CVC, but not connected
- Make sure the deployed app has NO network adapters (by configuring the VM this way)
- make sure there are NO available execution servers
- hit connect

Defect reproduces if:
- CVC has alias "Connecting" even after Apply Connectivity Changes command failed, and CVC appears as solid line (i.e. Connected==true)

Here is the JSON I got back:
	
'Apply Connectivity Changes' resource command on 'VMware vCenter' failed with 'Start Failed' error:
Error: Start Failed
Description: Execution server is unavailable
Parameters:

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by doppleware** [comment] 2016-03-20 15:04
Bug is only that it stays as 'connecting'

**Comment by nahumtimerman** [comment] 2016-03-20 15:12
Mind, should be connected=false since both endpoints failed to apply

**Comment by alexazarh** [comment] 2016-03-20 17:59
I think its not a bug. What actually happens here is that the "Connect" command is enqueued  in the execution server:
![image](https://cloud.githubusercontent.com/assets/6730546/13905925/854f16dc-eed5-11e5-91c5-fa7e364917fc.png)
By default there is no timeout for a command in a queued, so the connectivity service just waits for a reply. If after some time you will start an execution server and the command will try to run, it will fail because there are no nics:
![image](https://cloud.githubusercontent.com/assets/6730546/13905962/4b2a59b6-eed6-11e5-9978-c37b58f25bb4.png)

**Comment by alexazarh** [comment] 2016-03-20 18:02
@doppleware / @alonagetzler 
Do we want to add a timeout for ApplyConnectivityChanges when executed from the connectivity service?

**Comment by alexazarh** [comment] 2016-03-21 11:02
I added a timeout to the connectity commands executed on the Execution Server.
Default timeout is 600 sec.
It can be changed using the key "Connectivity.CommandExecutionTimeout" in customer.config

**Comment by TomerAdmon** [comment] 2016-03-26 16:41
@alonagetzler  - Alona, can we document it?

**Comment by alonagetzler** [comment] 2016-03-27 13:24
I’m not sure that we need to externally document it

**Comment by TomerAdmon** [comment] 2016-03-27 13:26
@alonagetzler  / @doppleware  - should we close the issue?

**Comment by alonagetzler** [comment] 2016-03-27 13:28
yep, the timeout is the right solution here

**Closed** 2016-03-27 13:38 UTC
Labels: bug, Connectivity, P2, ready to test
